<a href="https://colab.research.google.com/github/himanshi-15/Liar-Dataset-Fake-News-Detection-Ml-project-/blob/main/ML_BASIC_MODELS_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
train=pd.read_csv('/content/drive/MyDrive/liar_dataset/train.csv')

In [ ]:
test=pd.read_csv('/content/drive/MyDrive/liar_dataset/test.csv')

In [ ]:
df_raw = pd.concat([train, test], axis=0, sort=False)
df_raw = df_raw.sample(frac=1).reset_index()
df_raw.head(2)

index  ...                                           Context
0   2299  ...                             a campaign commercial
1   4389  ...  an oped article in the Austin American-Statesman

[2 rows x 15 columns]

In [ ]:
# The file contains 11507 rows and 15 columns
df_raw.shape

(11507, 15)

In [ ]:
# naming the columns of the dataset
df_raw.columns=["index","ID", "label", "statement", "subject", "speaker", "job", "state", "party", "barely_true_cts", "false_cts", "half_true_cts", "mostly_true_cts", "pants_on_fire_cts", "context"]

In [ ]:
# some of the statements
df_raw['statement'].head(10).tolist()

['He (Kirk) did violate Pentagon rules, twice actually, for improperly mingling politics with his military service.',
 'Texas has outstripped the national poverty rate since at least 1959.',
 'As mayor, every year I was in office I did reduce taxes.',
 'President Obama has spent over $2 million in legal fees defending lawsuits about his birth certificate.',
 'Woodrow Wilson borrowed $30 billion to fund World War I in 1917. That money has not been paid back. And we are still paying interest on it.',
 'Says Marco Rubio voted against every bill that would have helped keep our families safe. He even voted against a bipartisan measure, introduced by a Republican, to prevent people on the no-fly list from purchasing guns.',
 'Says close to 90 percent of the population growth in Texas over the last decade was non-Anglo.',
 'Rick Perry has become a millionaire on the public payroll.',
 'Says the Koch brothers want to protect tax cuts for companies that ship our jobs overseas.',
 'Kip Kinkel an

In [ ]:
#Checking for duplicates and removing them
df_raw.drop_duplicates(inplace = True)

In [ ]:
#Show the number of missing (NAN, NaN, na) data for each column
df_raw.isnull().sum()

index                   0
ID                      0
label                   0
statement               0
subject                 2
speaker                 2
job                  3222
state                2470
party                   2
barely_true_cts         2
false_cts               2
half_true_cts           2
mostly_true_cts         2
pants_on_fire_cts       2
context               119
dtype: int64

In [ ]:
# data cleaning 
df_raw["statement"]=df_raw["statement"].str.lower()
df_raw["subject"].fillna("",inplace=True)
df_raw["speaker"].fillna("",inplace=True)
df_raw["job"].fillna("",inplace=True)
df_raw["state"].fillna("",inplace=True)
df_raw["party"].fillna("",inplace=True)
df_raw["barely_true_cts"].fillna("",inplace=True)
df_raw["false_cts"].fillna("",inplace=True)
df_raw["half_true_cts"].fillna("",inplace=True)
df_raw["mostly_true_cts"].fillna("",inplace=True)
df_raw["pants_on_fire_cts"].fillna("",inplace=True)
df_raw["context"].fillna("",inplace=True)

df_raw.isnull().sum()

index                0
ID                   0
label                0
statement            0
subject              0
speaker              0
job                  0
state                0
party                0
barely_true_cts      0
false_cts            0
half_true_cts        0
mostly_true_cts      0
pants_on_fire_cts    0
context              0
dtype: int64

In [ ]:
import numpy as np
import nltk
from nltk.corpus import stopwords
import string
#Need to download stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
#Tokenization (a list of tokens), will be used as the analyzer
#1.Punctuations are [!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~]
#2.Stop words in natural language processing, are useless words (data).
import re
def process_text(text):
    
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub("\\W"," ",text) 
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text) 
    
    return text

In [ ]:
#Show the Tokenization (a list of tokens )
df_raw['statement'].head().apply(process_text)

0    he  kirk  did violate pentagon rules  twice ac...
1    texas has outstripped the national poverty rat...
2    as mayor  every year i was in office i did red...
3    president obama has spent over   million in le...
4    woodrow wilson borrowed   billion to fund worl...
Name: statement, dtype: object

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorization = TfidfVectorizer()
messages_bow = vectorization.fit_transform(df_raw['statement'])

In [ ]:
#Get the shape of messages_bow
messages_bow.shape

(11507, 12873)

In [ ]:
#Split data into 75% training & 25% testing data sets
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(messages_bow, df_raw['label'], test_size=0.25, random_state=7, shuffle=True)


# Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

logreg = LogisticRegression()
logreg.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
#Evaluate the model on the test data set
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
pred = logreg.predict(x_test)
print(classification_report(y_test ,pred ))
print('Confusion Matrix: \n', confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

       FALSE       0.28      0.33      0.31       598
        TRUE       0.28      0.22      0.25       467
 barely-true       0.20      0.18      0.19       442
   half-true       0.23      0.31      0.26       579
 mostly-true       0.23      0.26      0.25       558
  pants-fire       0.36      0.02      0.04       233

    accuracy                           0.25      2877
   macro avg       0.26      0.22      0.22      2877
weighted avg       0.26      0.25      0.24      2877

Confusion Matrix: 
 [[200  56  87 144 107   4]
 [ 97 103  43 112 112   0]
 [117  37  81 126  79   2]
 [115  63  77 178 143   3]
 [101  86  66 160 145   0]
 [ 75  20  45  55  33   5]]


In [ ]:
print('Accuracy: ', accuracy_score(y_test,pred))

Accuracy:  0.24748001390337157


# Naive Bayes

In [ ]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(x_train, y_train)

y_pred=classifier.predict(x_test)

In [ ]:
#Evaluate the model on the test data set
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
pred = classifier.predict(x_test)
print(classification_report(y_test ,pred ))
print('Confusion Matrix: \n', confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

       FALSE       0.29      0.23      0.25       598
        TRUE       0.26      0.04      0.07       467
 barely-true       0.26      0.06      0.10       442
   half-true       0.21      0.58      0.31       579
 mostly-true       0.22      0.27      0.24       558
  pants-fire       0.00      0.00      0.00       233

    accuracy                           0.23      2877
   macro avg       0.21      0.19      0.16      2877
weighted avg       0.23      0.23      0.19      2877

Confusion Matrix: 
 [[135  18  31 305 109   0]
 [ 66  19   7 242 133   0]
 [ 78   5  27 255  77   0]
 [ 67  14  15 334 149   0]
 [ 65  13   7 325 148   0]
 [ 52   4  16 119  42   0]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
print('Accuracy: ', accuracy_score(y_test,pred))

Accuracy:  0.23044838373305526


# KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

# Clustering the document with KNN classifier
modelknn = KNeighborsClassifier(n_neighbors=5)
modelknn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
#Evaluate the model on the test data set
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
pred = modelknn.predict(x_test)
print(classification_report(y_test ,pred ))
print('Confusion Matrix: \n', confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

       FALSE       0.25      0.37      0.29       598
        TRUE       0.20      0.22      0.21       467
 barely-true       0.17      0.17      0.17       442
   half-true       0.23      0.23      0.23       579
 mostly-true       0.26      0.17      0.21       558
  pants-fire       0.17      0.06      0.09       233

    accuracy                           0.22      2877
   macro avg       0.21      0.20      0.20      2877
weighted avg       0.22      0.22      0.22      2877

Confusion Matrix: 
 [[219 104  89 110  60  16]
 [133 104  63  79  75  13]
 [135  69  73  98  51  16]
 [158 108  82 134  75  22]
 [155 111  76 111  97   8]
 [ 90  28  37  44  19  15]]


In [ ]:
print('Accuracy: ', accuracy_score(y_test,pred))

Accuracy:  0.22314911366006257


# RANDOM FOREST

In [ ]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(x_train,y_train)

y_pred=clf.predict(x_test)

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
#Model Evaluation on test set

print(classification_report(y_test,y_pred))
print('Confusion Matrix: \n', confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

       FALSE       0.27      0.38      0.31       598
        TRUE       0.22      0.15      0.18       467
 barely-true       0.22      0.15      0.18       442
   half-true       0.23      0.30      0.26       579
 mostly-true       0.23      0.27      0.25       558
  pants-fire       0.54      0.06      0.10       233

    accuracy                           0.24      2877
   macro avg       0.29      0.22      0.21      2877
weighted avg       0.26      0.24      0.23      2877

Confusion Matrix: 
 [[228  61  53 152  99   5]
 [108  68  36 117 137   1]
 [140  35  65 122  79   1]
 [157  56  52 174 138   2]
 [131  77  49 151 148   2]
 [ 88  12  34  53  33  13]]


In [ ]:
print('Accuracy: ', accuracy_score(y_test,y_pred))

Accuracy:  0.24191866527632952


# SUPPORT VECTOR MACHINE (SVM)

In [ ]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel="poly")
#Train the model using the training sets
clf.fit(x_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(x_test)

In [ ]:
#Evaluate the model on the test data set
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
print(classification_report(y_test ,y_pred))
print('Confusion Matrix: \n', confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

       FALSE       0.34      0.14      0.20       598
        TRUE       0.48      0.03      0.05       467
 barely-true       0.50      0.02      0.05       442
   half-true       0.21      0.85      0.33       579
 mostly-true       0.30      0.11      0.16       558
  pants-fire       1.00      0.01      0.03       233

    accuracy                           0.23      2877
   macro avg       0.47      0.19      0.14      2877
weighted avg       0.41      0.23      0.16      2877

Confusion Matrix: 
 [[ 86   0   3 484  25   0]
 [ 31  13   1 384  38   0]
 [ 49   4  11 357  21   0]
 [ 28   5   4 494  48   0]
 [ 36   5   3 455  59   0]
 [ 26   0   0 198   6   3]]


In [ ]:
print('Accuracy: ', accuracy_score(y_test,pred))

# Decision Tree


In [ ]:
# Import Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier 

In [ ]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(x_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(x_test)

In [ ]:
#Evaluate the model on the test data set
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score 
print(classification_report(y_test ,y_pred))
print('Confusion Matrix: \n', confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

       FALSE       0.24      0.27      0.25       557
        TRUE       0.19      0.16      0.17       468
 barely-true       0.18      0.18      0.18       474
   half-true       0.20      0.20      0.20       605
 mostly-true       0.22      0.23      0.22       558
  pants-fire       0.12      0.12      0.12       215

    accuracy                           0.20      2877
   macro avg       0.19      0.19      0.19      2877
weighted avg       0.20      0.20      0.20      2877

Confusion Matrix: 
 [[148  65  88 121  90  45]
 [ 93  74  63  99 108  31]
 [ 99  49  83 114  88  41]
 [129  89  97 124 134  32]
 [ 98  90  86 119 129  36]
 [ 52  16  46  36  40  25]]


In [ ]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.20264164059784498
